---
- hosts: jenkins
  become: true
  gather_facts: yes


  tasks:

  - name: Install Java latest
    yum:
       name: java
       state: latest

  - name: Create Jenkins Repo
    get_url: 
       url: https://pkg.jenkins.io/redhat/jenkins.repo
       dest: /etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins Key
    rpm_key:
       state: present
       key: https://pkg.jenkins.io/redhat/jenkins.io.key

  - name: Install jenkins
    yum:
       name: jenkins
       state: latest

  - name: Start & enable jenkins server
    service: 
       name: jenkins
       state: started
       enabled: yes
